// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using FleetManage.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FleetManage.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251231002128_RefactorServicePartnerAddress")]
    partial class RefactorServicePartnerAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FleetManage.Api.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.Department", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("IndustryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("ListEquipment")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Code = "OPS",
                            IndustryId = 2,
                            IsActive = true,
                            ListEquipment = true,
                            Name = "Fleet Operations"
                        },
                        new
                        {
                            Id = 102,
                            Code = "MNT",
                            IndustryId = 2,
                            IsActive = true,
                            ListEquipment = false,
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = 103,
                            Code = "YRD",
                            IndustryId = 2,
                            IsActive = true,
                            ListEquipment = false,
                            Name = "Yard & Terminal"
                        },
                        new
                        {
                            Id = 201,
                            Code = "MOV",
                            IndustryId = 1,
                            IsActive = true,
                            ListEquipment = true,
                            Name = "Earthmoving"
                        },
                        new
                        {
                            Id = 202,
                            Code = "LFT",
                            IndustryId = 1,
                            IsActive = true,
                            ListEquipment = true,
                            Name = "Lifting & Handling"
                        },
                        new
                        {
                            Id = 203,
                            Code = "PAV",
                            IndustryId = 1,
                            IsActive = true,
                            ListEquipment = true,
                            Name = "Road & Paving"
                        },
                        new
                        {
                            Id = 204,
                            Code = "CON",
                            IndustryId = 1,
                            IsActive = true,
                            ListEquipment = true,
                            Name = "Concrete"
                        },
                        new
                        {
                            Id = 205,
                            Code = "UTL",
                            IndustryId = 1,
                            IsActive = true,
                            ListEquipment = true,
                            Name = "Utilities & Support"
                        },
                        new
                        {
                            Id = 206,
                            Code = "DEM",
                            IndustryId = 1,
                            IsActive = true,
                            ListEquipment = true,
                            Name = "Demolition"
                        },
                        new
                        {
                            Id = 207,
                            Code = "LOG",
                            IndustryId = 1,
                            IsActive = true,
                            ListEquipment = false,
                            Name = "Site Logistics"
                        });
                });

            modelBuilder.Entity("FleetManage.Api.Data.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("ExtractedJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ExtractedJson");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorNameRaw")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.DocumentLink", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("DocumentId");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("EntityType");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("TenantId", "DocumentId", "EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("DocumentLinks", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("AcquiredDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("EquipmentTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("HoursCurrent")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("InServiceDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<short>("LifecycleStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("Make")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("OdometerCurrent")
                        .HasColumnType("integer");

                    b.Property<short>("OperationalStatus")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("OutOfServiceDate")
                        .HasColumnType("date");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vin")
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EquipmentTypeId");

                    b.HasIndex("TenantId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("FleetManage.Api.Data.EquipmentDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid");

                    b.Property<short>("DocRole")
                        .HasColumnType("smallint");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EquipmentId", "DocumentId")
                        .IsUnique();

                    b.ToTable("EquipmentDocuments", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasSerial")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasVin")
                        .HasColumnType("boolean");

                    b.Property<int>("IndustryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MeterMode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("IndustryId");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Code = "TRCTR",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Tractor (Semi Truck)"
                        },
                        new
                        {
                            Id = 1002,
                            Code = "DAY",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Day Cab Truck"
                        },
                        new
                        {
                            Id = 1003,
                            Code = "SLP",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Sleeper Truck"
                        },
                        new
                        {
                            Id = 1004,
                            Code = "STR",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Straight Truck"
                        },
                        new
                        {
                            Id = 1005,
                            Code = "BOX",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Box Truck"
                        },
                        new
                        {
                            Id = 1006,
                            Code = "VAN",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Cargo Van"
                        },
                        new
                        {
                            Id = 1007,
                            Code = "PUP",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Pickup Truck"
                        },
                        new
                        {
                            Id = 1101,
                            Code = "DV",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Dry Van Trailer"
                        },
                        new
                        {
                            Id = 1102,
                            Code = "RFR",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Refrigerated Trailer (Reefer)"
                        },
                        new
                        {
                            Id = 1103,
                            Code = "FLT",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Flatbed Trailer"
                        },
                        new
                        {
                            Id = 1104,
                            Code = "STD",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Step Deck Trailer"
                        },
                        new
                        {
                            Id = 1105,
                            Code = "LBY",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Lowboy Trailer"
                        },
                        new
                        {
                            Id = 1106,
                            Code = "TNK",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Tanker Trailer"
                        },
                        new
                        {
                            Id = 1107,
                            Code = "DMP",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Dump Trailer"
                        },
                        new
                        {
                            Id = 1108,
                            Code = "CHS",
                            DepartmentId = 101,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Intermodal Chassis"
                        },
                        new
                        {
                            Id = 1201,
                            Code = "SVC",
                            DepartmentId = 102,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Service Truck"
                        },
                        new
                        {
                            Id = 1202,
                            Code = "MMT",
                            DepartmentId = 102,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Mobile Mechanic Truck"
                        },
                        new
                        {
                            Id = 1203,
                            Code = "TIRE",
                            DepartmentId = 102,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Tire Service Unit"
                        },
                        new
                        {
                            Id = 1204,
                            Code = "FUEL",
                            DepartmentId = 102,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Fuel Service Truck"
                        },
                        new
                        {
                            Id = 1301,
                            Code = "YRD",
                            DepartmentId = 103,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Yard Tractor (Spotter)"
                        },
                        new
                        {
                            Id = 1302,
                            Code = "TRM",
                            DepartmentId = 103,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Terminal Tractor"
                        },
                        new
                        {
                            Id = 1303,
                            Code = "GEN",
                            DepartmentId = 103,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Generator"
                        },
                        new
                        {
                            Id = 1304,
                            Code = "LGT",
                            DepartmentId = 103,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Light Tower"
                        },
                        new
                        {
                            Id = 1305,
                            Code = "OFF",
                            DepartmentId = 103,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 2,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Mobile Office Trailer"
                        },
                        new
                        {
                            Id = 2001,
                            Code = "EXC",
                            DepartmentId = 201,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Excavator"
                        },
                        new
                        {
                            Id = 2002,
                            Code = "MEX",
                            DepartmentId = 201,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Mini Excavator"
                        },
                        new
                        {
                            Id = 2003,
                            Code = "DOZ",
                            DepartmentId = 201,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Bulldozer"
                        },
                        new
                        {
                            Id = 2004,
                            Code = "WLD",
                            DepartmentId = 201,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Wheel Loader"
                        },
                        new
                        {
                            Id = 2005,
                            Code = "SSL",
                            DepartmentId = 201,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Skid Steer Loader"
                        },
                        new
                        {
                            Id = 2006,
                            Code = "CTL",
                            DepartmentId = 201,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Compact Track Loader"
                        },
                        new
                        {
                            Id = 2007,
                            Code = "BHL",
                            DepartmentId = 201,
                            HasSerial = true,
                            HasVin = true,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 3,
                            Name = "Backhoe Loader"
                        },
                        new
                        {
                            Id = 2008,
                            Code = "GRD",
                            DepartmentId = 201,
                            HasSerial = true,
                            HasVin = true,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 3,
                            Name = "Motor Grader"
                        },
                        new
                        {
                            Id = 2101,
                            Code = "FLK",
                            DepartmentId = 202,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Forklift"
                        },
                        new
                        {
                            Id = 2102,
                            Code = "RTF",
                            DepartmentId = 202,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Rough Terrain Forklift"
                        },
                        new
                        {
                            Id = 2103,
                            Code = "TEL",
                            DepartmentId = 202,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Telehandler"
                        },
                        new
                        {
                            Id = 2104,
                            Code = "CRN",
                            DepartmentId = 202,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Mobile Crane"
                        },
                        new
                        {
                            Id = 2105,
                            Code = "TCR",
                            DepartmentId = 202,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Tower Crane"
                        },
                        new
                        {
                            Id = 2106,
                            Code = "BML",
                            DepartmentId = 202,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Boom Lift"
                        },
                        new
                        {
                            Id = 2107,
                            Code = "SCL",
                            DepartmentId = 202,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Scissor Lift"
                        },
                        new
                        {
                            Id = 2201,
                            Code = "ROL",
                            DepartmentId = 203,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Road Roller (Compactor)"
                        },
                        new
                        {
                            Id = 2202,
                            Code = "PAV",
                            DepartmentId = 203,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Asphalt Paver"
                        },
                        new
                        {
                            Id = 2203,
                            Code = "MIL",
                            DepartmentId = 203,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Cold Planer (Milling)"
                        },
                        new
                        {
                            Id = 2204,
                            Code = "SCP",
                            DepartmentId = 203,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Soil Compactor"
                        },
                        new
                        {
                            Id = 2205,
                            Code = "PLC",
                            DepartmentId = 203,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Plate Compactor"
                        },
                        new
                        {
                            Id = 2301,
                            Code = "CMT",
                            DepartmentId = 204,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Concrete Mixer Truck"
                        },
                        new
                        {
                            Id = 2302,
                            Code = "CPT",
                            DepartmentId = 204,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Concrete Pump Truck"
                        },
                        new
                        {
                            Id = 2303,
                            Code = "CBP",
                            DepartmentId = 204,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Concrete Batching Plant"
                        },
                        new
                        {
                            Id = 2304,
                            Code = "PTR",
                            DepartmentId = 204,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Power Trowel"
                        },
                        new
                        {
                            Id = 2305,
                            Code = "CSW",
                            DepartmentId = 204,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Concrete Saw"
                        },
                        new
                        {
                            Id = 2401,
                            Code = "GEN",
                            DepartmentId = 205,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Generator"
                        },
                        new
                        {
                            Id = 2402,
                            Code = "ACM",
                            DepartmentId = 205,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Air Compressor"
                        },
                        new
                        {
                            Id = 2403,
                            Code = "LGT",
                            DepartmentId = 205,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Light Tower"
                        },
                        new
                        {
                            Id = 2404,
                            Code = "WLDG",
                            DepartmentId = 205,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Welding Machine"
                        },
                        new
                        {
                            Id = 2405,
                            Code = "PWSH",
                            DepartmentId = 205,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Pressure Washer"
                        },
                        new
                        {
                            Id = 2501,
                            Code = "DEX",
                            DepartmentId = 206,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Demolition Excavator"
                        },
                        new
                        {
                            Id = 2502,
                            Code = "HBR",
                            DepartmentId = 206,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Hydraulic Breaker"
                        },
                        new
                        {
                            Id = 2503,
                            Code = "CRS",
                            DepartmentId = 206,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Crusher"
                        },
                        new
                        {
                            Id = 2504,
                            Code = "SCR",
                            DepartmentId = 206,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Screener"
                        },
                        new
                        {
                            Id = 2601,
                            Code = "DMP",
                            DepartmentId = 207,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Dump Truck"
                        },
                        new
                        {
                            Id = 2602,
                            Code = "ADT",
                            DepartmentId = 207,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 2,
                            Name = "Articulated Dump Truck"
                        },
                        new
                        {
                            Id = 2603,
                            Code = "WTR",
                            DepartmentId = 207,
                            HasSerial = false,
                            HasVin = true,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 1,
                            Name = "Water Truck"
                        },
                        new
                        {
                            Id = 2604,
                            Code = "STRL",
                            DepartmentId = 207,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Site Trailer"
                        },
                        new
                        {
                            Id = 2605,
                            Code = "MOFF",
                            DepartmentId = 207,
                            HasSerial = true,
                            HasVin = false,
                            IndustryId = 1,
                            IsActive = true,
                            MeterMode = 0,
                            Name = "Mobile Office"
                        });
                });

            modelBuilder.Entity("FleetManage.Api.Data.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Construction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trucking & Logistics"
                        });
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServiceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("ExtractedJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<int?>("Odometer")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorNameRaw")
                        .HasColumnType("text");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("VendorId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ServiceHistories");
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServiceHistoryLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ServiceHistoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ServiceHistoryId");

                    b.ToTable("ServiceHistoryLines");
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServicePartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<decimal?>("AuditScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("numeric");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LaborRate")
                        .HasColumnType("numeric");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NetworkTier")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PricingStrategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<List<string>>("Specialties")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("ServicePartners", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServicePartnerRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .HasColumnType("text");

                    b.Property<Guid>("ServicePartnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServicePartnerId");

                    b.ToTable("ServicePartnerRatings", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int?>("IndustryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Complaint")
                        .HasColumnType("text");

                    b.Property<string>("CostSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("EquipmentId");

                    b.Property<decimal?>("EstimatedTotal")
                        .HasColumnType("numeric");

                    b.Property<int?>("HoursAtService")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<decimal?>("ManualActualTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("OdometerAtService")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Priority");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("VendorId");

                    b.Property<string>("WorkOrderNumber")
                        .HasColumnType("text")
                        .HasColumnName("WorkOrderNumber");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("VendorId");

                    b.ToTable("WorkOrders", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrderDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AddedBy")
                        .HasColumnType("uuid");

                    b.Property<short>("DocRole")
                        .HasColumnType("smallint");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WorkOrderId", "DocumentId")
                        .IsUnique();

                    b.ToTable("WorkOrderDocuments", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrderInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderInvoices", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrderLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderLineItems", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FleetManage.Api.Data.AppUser", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FleetManage.Api.Data.Department", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("FleetManage.Api.Data.DocumentLink", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("FleetManage.Api.Data.Equipment", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManage.Api.Data.EquipmentType", "EquipmentType")
                        .WithMany()
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("FleetManage.Api.Data.EquipmentDocument", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Document", "Document")
                        .WithMany("EquipmentDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManage.Api.Data.Equipment", "Equipment")
                        .WithMany("EquipmentDocuments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("FleetManage.Api.Data.EquipmentType", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManage.Api.Data.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServiceHistory", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManage.Api.Data.ServicePartner", "ServicePartner")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FleetManage.Api.Data.WorkOrder", "WorkOrder")
                        .WithMany()
                        .HasForeignKey("WorkOrderId");

                    b.Navigation("Equipment");

                    b.Navigation("ServicePartner");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServiceHistoryLine", b =>
                {
                    b.HasOne("FleetManage.Api.Data.ServiceHistory", "ServiceHistory")
                        .WithMany("Lines")
                        .HasForeignKey("ServiceHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceHistory");
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServicePartner", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServicePartnerRating", b =>
                {
                    b.HasOne("FleetManage.Api.Data.ServicePartner", "ServicePartner")
                        .WithMany("Ratings")
                        .HasForeignKey("ServicePartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePartner");
                });

            modelBuilder.Entity("FleetManage.Api.Data.Tenant", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrder", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Equipment", "Equipment")
                        .WithMany("WorkOrders")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("FleetManage.Api.Data.ServicePartner", "Vendor")
                        .WithMany("WorkOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrderDocument", b =>
                {
                    b.HasOne("FleetManage.Api.Data.Document", "Document")
                        .WithMany("WorkOrderDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManage.Api.Data.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderDocuments")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrderInvoice", b =>
                {
                    b.HasOne("FleetManage.Api.Data.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderInvoices")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrderLineItem", b =>
                {
                    b.HasOne("FleetManage.Api.Data.WorkOrder", "WorkOrder")
                        .WithMany("LineItems")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FleetManage.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FleetManage.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FleetManage.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FleetManage.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FleetManage.Api.Data.Document", b =>
                {
                    b.Navigation("EquipmentDocuments");

                    b.Navigation("WorkOrderDocuments");
                });

            modelBuilder.Entity("FleetManage.Api.Data.Equipment", b =>
                {
                    b.Navigation("EquipmentDocuments");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServiceHistory", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("FleetManage.Api.Data.ServicePartner", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("FleetManage.Api.Data.Tenant", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FleetManage.Api.Data.WorkOrder", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("WorkOrderDocuments");

                    b.Navigation("WorkOrderInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
